version: '3'
services:

  postgres:
    image: timescale/timescaledb:latest-pg12
    ports:
      - "49514:5432"
    volumes:
      - lusankya_postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lusankya

volumes:
  lusankya_postgres: